version: '3.8'

services:
  database:
    image: postgres:11
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ls
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    image: nginx:1.19.6-alpine
    restart: on-failure
    volumes:
      - './apps/backend/public/:/usr/src/app'
      - './docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 8002:80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './apps/backend/:/usr/src/app'
    restart: on-failure
    user: 1000:1000
networks:
  default:
